//! Byte-exact checks against layouts produced by a real C++ compiler.
//!
//! `tests/golden_vectors.txt` is generated by `tools/golden/gen_golden.cpp`,
//! which carries the `enow_text_msg_t` and `enow_admin_msg_t` typedefs copied
//! verbatim from the firmware's `src/WiFiOps.h`. Regenerate with:
//!
//! ```text
//! c++ -std=c++17 -Wall -Wextra -o /tmp/gen_golden tools/golden/gen_golden.cpp
//! /tmp/gen_golden > crates/wartui-proto/tests/golden_vectors.txt
//! ```
//!
//! Frames captured off the air by the Phase 0 sniffer can be appended to the
//! same file in the same `name len hex` format and will be exercised too.

use wartui_proto::air::{
    ADMIN_MSG_LEN, AdminMsg, DecodeError, Frame, MsgType, TEXT_MSG_LEN, TextMsg,
};

const GOLDEN: &str = include_str!("golden_vectors.txt");

fn vector(name: &str) -> Vec<u8> {
    for line in GOLDEN.lines() {
        let mut parts = line.split_whitespace();
        if line.starts_with('#') || parts.next() != Some(name) {
            continue;
        }
        let len: usize = parts.next().expect("length field").parse().expect("numeric length");
        let hex = parts.next().expect("hex field");
        let bytes: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex byte"))
            .collect();
        assert_eq!(bytes.len(), len, "{name}: declared length disagrees with payload");
        return bytes;
    }
    panic!("no golden vector named {name}");
}

#[test]
fn struct_sizes_match_the_compiler() {
    assert_eq!(vector("heartbeat").len(), TEXT_MSG_LEN);
    assert_eq!(vector("admin").len(), ADMIN_MSG_LEN);
}

#[test]
fn heartbeat_encodes_byte_for_byte() {
    let msg = TextMsg::new(MsgType::Heartbeat, 0x1234_5678, b"").expect("empty text fits");
    assert_eq!(msg.encode().as_slice(), vector("heartbeat").as_slice());
}

#[test]
fn wifi_text_encodes_byte_for_byte() {
    let line = b"AA:BB:CC:DD:EE:FF,My_Net,[WPA2_PSK],11,-42,W";
    let msg = TextMsg::new(MsgType::Text, 0, line).expect("line fits");
    assert_eq!(msg.encode().as_slice(), vector("text_wifi").as_slice());
}

#[test]
fn ble_text_encodes_byte_for_byte() {
    let line = b"aa:bb:cc:dd:ee:ff,,[BLE],0,-70,B";
    let msg = TextMsg::new(MsgType::Text, 0, line).expect("line fits");
    assert_eq!(msg.encode().as_slice(), vector("text_ble").as_slice());
}

#[test]
fn core_request_encodes_byte_for_byte() {
    let msg = TextMsg::new(MsgType::CoreRequest, 0, b"").expect("empty text fits");
    assert_eq!(msg.encode().as_slice(), vector("core_request").as_slice());
}

#[test]
fn admin_encodes_byte_for_byte() {
    let msg = AdminMsg {
        assignment_version: 7,
        node_index: 2,
        node_count: 5,
        start_channel_idx: 16,
        end_channel_idx: 23,
    };
    assert_eq!(msg.encode().as_slice(), vector("admin").as_slice());
}

#[test]
fn every_golden_vector_round_trips() {
    // `#` lines are the sniffer's commentary, so a capture log can be pasted
    // in unedited.
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')) {
        let name = line.split_whitespace().next().expect("name");
        let bytes = vector(name);
        let frame = Frame::decode(&bytes).unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));
        let reencoded = match frame {
            Frame::Text(m) => m.encode().to_vec(),
            Frame::Admin(m) => m.encode().to_vec(),
        };
        assert_eq!(reencoded, bytes, "{name}: re-encode differs, including zero padding");
    }
}

#[test]
fn decoded_fields_match_what_the_generator_wrote() {
    let bytes = vector("heartbeat");
    let msg = TextMsg::decode(&bytes).expect("valid heartbeat");
    assert_eq!(msg.msg_type, MsgType::Heartbeat);
    assert_eq!(msg.counter, 0x1234_5678, "counter must be read little-endian");
    assert!(msg.text.is_empty());

    let bytes = vector("text_wifi");
    let msg = TextMsg::decode(&bytes).expect("valid text");
    assert_eq!(msg.text, b"AA:BB:CC:DD:EE:FF,My_Net,[WPA2_PSK],11,-42,W");

    let bytes = vector("admin");
    let msg = AdminMsg::decode(&bytes).expect("valid admin");
    assert_eq!(msg.assignment_version, 7);
    assert_eq!(msg.node_index, 2);
    assert_eq!(msg.node_count, 5);
    assert_eq!(msg.start_channel_idx, 16);
    assert_eq!(msg.end_channel_idx, 23);
}

#[test]
fn short_frames_are_rejected_like_the_firmware_does() {
    // Every receive handler bails with `if (len < sizeof(...)) return;`, so a
    // 211-byte text frame is not a text frame.
    let bytes = vector("text_wifi");
    assert!(matches!(
        TextMsg::decode(&bytes[..TEXT_MSG_LEN - 1]),
        Err(DecodeError::TooShort { need: TEXT_MSG_LEN, got: 211 })
    ));

    let admin = vector("admin");
    assert!(matches!(
        AdminMsg::decode(&admin[..ADMIN_MSG_LEN - 1]),
        Err(DecodeError::TooShort { .. })
    ));
    assert!(matches!(Frame::decode(&admin[..4]), Err(DecodeError::TooShort { need: 5, got: 4 })));
}

#[test]
fn bad_magic_and_unknown_types_are_rejected() {
    let mut bytes = vector("text_wifi");
    bytes[0] = b'X';
    assert_eq!(Frame::decode(&bytes), Err(DecodeError::BadMagic));

    let mut bytes = vector("text_wifi");
    bytes[4] = 9;
    assert_eq!(Frame::decode(&bytes), Err(DecodeError::UnknownType(9)));
}

#[test]
fn oversized_text_length_is_rejected() {
    let mut bytes = vector("text_wifi");
    bytes[9..11].copy_from_slice(&201u16.to_le_bytes());
    assert_eq!(TextMsg::decode(&bytes), Err(DecodeError::TextTooLong(201)));

    let too_long = [b'x'; 201];
    assert_eq!(TextMsg::new(MsgType::Text, 0, &too_long), Err(DecodeError::TextTooLong(201)));
}

#[test]
fn captured_observation_payloads_parse_as_wardrive_lines() {
    // The round-trip test proves the frame layout survives; this proves the
    // payload format does. They fail independently: the firmware could change
    // its comma-separated line without touching the struct around it.
    use wartui_proto::air::{RecordKind, WardriveLine};

    let mut parsed = 0;
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')) {
        let name = line.split_whitespace().next().expect("name");
        let bytes = vector(name);
        let Ok(Frame::Text(msg)) = Frame::decode(&bytes) else { continue };
        // Heartbeats and pairing requests carry no payload.
        if msg.msg_type != MsgType::Text || msg.text.is_empty() {
            continue;
        }
        let record = WardriveLine::parse(msg.text)
            .unwrap_or_else(|e| panic!("{name}: {e} in {:?}", String::from_utf8_lossy(msg.text)));
        match record.kind {
            RecordKind::Ble => {
                assert_eq!(record.channel, 0, "{name}: BLE records carry channel 0");
                assert!(record.ssid.is_empty(), "{name}: BLE records carry no SSID");
            }
            RecordKind::Wifi => assert!(record.channel > 0, "{name}: Wi-Fi needs a real channel"),
        }
        assert!(record.rssi < 0, "{name}: RSSI should be negative dBm");
        parsed += 1;
    }
    assert!(parsed >= 3, "expected several observation payloads, parsed {parsed}");
}

#[test]
fn the_real_cores_assignment_matches_what_our_planner_produces() {
    // The captured MSG_ADMIN frames come from the vendor core assigning its one
    // node. Reproducing them exactly is the whole contract wartui has to meet
    // when it takes that core's place, and it is checked here against the
    // core's actual bytes rather than against my reading of its source.
    use wartui_proto::plan::{ChannelPool, plan};

    let mut checked = 0;
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')) {
        let name = line.split_whitespace().next().expect("name");
        let bytes = vector(name);
        let Ok(Frame::Admin(observed)) = Frame::decode(&bytes) else { continue };

        // Stock nodes are assigned across the whole table, which is the `All`
        // pool. This covers the one-node capture from hardware and the
        // five-node split from the generated vector alike.
        let ours = plan(ChannelPool::All, observed.node_count)
            .expect("one node is a valid fleet")
            .admin_for(observed.node_index, 0, observed.assignment_version)
            .expect("node 0 is assigned");

        assert_eq!(ours, observed, "{name}: our assignment differs from the real core's");
        assert_eq!(ours.encode(), bytes.as_slice(), "{name}: our encoding differs byte-for-byte");
        checked += 1;
    }
    assert!(checked > 0, "no MSG_ADMIN frames in the fixture");
}
