//! Byte-exact checks against layouts produced by a real C++ compiler.
//!
//! `tests/golden_vectors.txt` is generated by `tools/golden/gen_golden.cpp`,
//! which carries the `enow_text_msg_t` and `enow_admin_msg_t` typedefs copied
//! verbatim from the firmware's `src/WiFiOps.h`. Regenerate with:
//!
//! ```text
//! c++ -std=c++17 -Wall -Wextra -o /tmp/gen_golden tools/golden/gen_golden.cpp
//! /tmp/gen_golden > crates/wartui-proto/tests/golden_vectors.txt
//! ```
//!
//! Frames captured off the air by the Phase 0 sniffer can be appended to the
//! same file in the same `name len hex` format and will be exercised too.
//!
//! The `admin*` vectors are the one thing in there that no compiler wrote:
//! from Phase 2 the core → node frame is wartui's own and has no C++ typedef
//! to be authoritative against. They are hand-written and checked here in both
//! directions, which is the most that can be said for a format with only one
//! implementation of each end.
//!
//! Something was given up to get there, and it is worth naming. Until Phase 2
//! this file also proved that wartui's planner reproduced a real vendor core's
//! assignment byte for byte, against frames sniffed off that core — the
//! strongest evidence available that wartui could take its place. Our
//! assignment is a different frame now, so there is nothing left to compare it
//! against: what the planner does is checked in `tests/planner.rs` against
//! properties rather than against another implementation.

use wartui_proto::air::{
    ADMIN_FLAG_BLE, ADMIN_MSG_LEN, AdminMsg, DecodeError, Frame, LEGACY_ADMIN_MSG_LEN, MsgType,
    TEXT_MSG_LEN, TextMsg, is_legacy_admin,
};
use wartui_proto::plan::{ChannelSet, IndexRun};

const GOLDEN: &str = include_str!("golden_vectors.txt");

fn vector(name: &str) -> Vec<u8> {
    for line in GOLDEN.lines() {
        let mut parts = line.split_whitespace();
        if line.starts_with('#') || parts.next() != Some(name) {
            continue;
        }
        let len: usize = parts.next().expect("length field").parse().expect("numeric length");
        let hex = parts.next().expect("hex field");
        let bytes: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("hex byte"))
            .collect();
        assert_eq!(bytes.len(), len, "{name}: declared length disagrees with payload");
        return bytes;
    }
    panic!("no golden vector named {name}");
}

#[test]
fn struct_sizes_match_the_compiler() {
    assert_eq!(vector("heartbeat").len(), TEXT_MSG_LEN);
    assert_eq!(vector("legacy_admin").len(), LEGACY_ADMIN_MSG_LEN);
    // Not the compiler's, but the same contract: everything that builds one of
    // these writes exactly this many bytes.
    assert_eq!(vector("admin").len(), ADMIN_MSG_LEN);
}

#[test]
fn heartbeat_encodes_byte_for_byte() {
    let msg = TextMsg::new(MsgType::Heartbeat, 0x1234_5678, b"").expect("empty text fits");
    assert_eq!(msg.encode().as_slice(), vector("heartbeat").as_slice());
}

#[test]
fn wifi_text_encodes_byte_for_byte() {
    let line = b"AA:BB:CC:DD:EE:FF,My_Net,[WPA2_PSK],11,-42,W";
    let msg = TextMsg::new(MsgType::Text, 0, line).expect("line fits");
    assert_eq!(msg.encode().as_slice(), vector("text_wifi").as_slice());
}

#[test]
fn ble_text_encodes_byte_for_byte() {
    let line = b"aa:bb:cc:dd:ee:ff,,[BLE],0,-70,B";
    let msg = TextMsg::new(MsgType::Text, 0, line).expect("line fits");
    assert_eq!(msg.encode().as_slice(), vector("text_ble").as_slice());
}

#[test]
fn core_request_encodes_byte_for_byte() {
    let msg = TextMsg::new(MsgType::CoreRequest, 0, b"").expect("empty text fits");
    assert_eq!(msg.encode().as_slice(), vector("core_request").as_slice());
}

#[test]
fn admin_encodes_byte_for_byte() {
    // The same assignment the vendor core's `legacy_admin` vector carries —
    // version 7, node 2 of 5, indices 16..=23 — said with a mask.
    let msg = AdminMsg {
        assignment_version: 7,
        node_index: 2,
        node_count: 5,
        flags: 0,
        channels: ChannelSet::from_run(IndexRun::new(16, 23)),
    };
    assert_eq!(msg.encode().as_slice(), vector("admin").as_slice());
}

#[test]
fn the_channel_mask_goes_out_least_significant_byte_first() {
    // Four indices chosen to straddle byte boundaries and to reach the top of
    // the forty, so a mask written big-endian — or in four bytes rather than
    // five — cannot produce these bytes.
    let mut channels = ChannelSet::empty();
    for idx in [0, 6, 13, 39] {
        channels.insert(idx);
    }
    let msg = AdminMsg {
        assignment_version: 200,
        node_index: 0,
        node_count: 1,
        flags: ADMIN_FLAG_BLE,
        channels,
    };
    assert_eq!(msg.encode().as_slice(), vector("admin_ble").as_slice());

    let back = AdminMsg::decode(&vector("admin_ble")).expect("valid admin");
    assert_eq!(back.channels.indices().collect::<Vec<_>>(), vec![0, 6, 13, 39]);
    assert!(back.scan_ble());
}

#[test]
fn the_vendors_assignment_is_recognised_without_being_obeyed() {
    // A stock core in the same room assigns wartui's nodes channels wartui did
    // not choose. Nothing decodes the frame — its fields are that core's idea
    // of the fleet — but it has to be told apart from line noise, because it is
    // the only visible cause of a fleet that keeps changing its mind.
    let legacy = vector("legacy_admin");
    assert!(is_legacy_admin(&legacy));
    assert!(matches!(
        AdminMsg::decode(&legacy),
        Err(DecodeError::TooShort { need: ADMIN_MSG_LEN, got: LEGACY_ADMIN_MSG_LEN })
    ));

    // Captured off the air: a real vendor core's assignment to its one node.
    assert!(is_legacy_admin(&vector("hw2_0071")));

    // And nothing else is mistaken for one. The length is exact because
    // ESP-NOW delivers a frame at the length it was sent.
    assert!(!is_legacy_admin(&vector("admin")), "ours is fourteen bytes");
    assert!(!is_legacy_admin(&vector("heartbeat")), "wrong type byte");
    assert!(!is_legacy_admin(&legacy[..9]), "truncated is not the vendor's shape");
    let mut wrong_magic = legacy.clone();
    wrong_magic[0] = b'X';
    assert!(!is_legacy_admin(&wrong_magic));
}

#[test]
fn every_golden_vector_round_trips() {
    // `#` lines are the sniffer's commentary, so a capture log can be pasted
    // in unedited.
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')) {
        let name = line.split_whitespace().next().expect("name");
        let bytes = vector(name);
        // The vendor's ten-byte assignment is deliberately not decodable; the
        // test above is the one that covers it.
        if is_legacy_admin(&bytes) {
            continue;
        }
        let frame = Frame::decode(&bytes).unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));
        let reencoded = match frame {
            Frame::Text(m) => m.encode().to_vec(),
            Frame::Admin(m) => m.encode().to_vec(),
        };
        assert_eq!(reencoded, bytes, "{name}: re-encode differs, including zero padding");
    }
}

#[test]
fn decoded_fields_match_what_the_generator_wrote() {
    let bytes = vector("heartbeat");
    let msg = TextMsg::decode(&bytes).expect("valid heartbeat");
    assert_eq!(msg.msg_type, MsgType::Heartbeat);
    assert_eq!(msg.counter, 0x1234_5678, "counter must be read little-endian");
    assert!(msg.text.is_empty());

    let bytes = vector("text_wifi");
    let msg = TextMsg::decode(&bytes).expect("valid text");
    assert_eq!(msg.text, b"AA:BB:CC:DD:EE:FF,My_Net,[WPA2_PSK],11,-42,W");

    let bytes = vector("admin");
    let msg = AdminMsg::decode(&bytes).expect("valid admin");
    assert_eq!(msg.assignment_version, 7);
    assert_eq!(msg.node_index, 2);
    assert_eq!(msg.node_count, 5);
    assert!(!msg.scan_ble());
    assert_eq!(msg.channels.indices().collect::<Vec<_>>(), (16..=23).collect::<Vec<_>>());
}

#[test]
fn short_frames_are_rejected_like_the_firmware_does() {
    // Every receive handler bails with `if (len < sizeof(...)) return;`, so a
    // 211-byte text frame is not a text frame.
    let bytes = vector("text_wifi");
    assert!(matches!(
        TextMsg::decode(&bytes[..TEXT_MSG_LEN - 1]),
        Err(DecodeError::TooShort { need: TEXT_MSG_LEN, got: 211 })
    ));

    let admin = vector("admin");
    assert!(matches!(
        AdminMsg::decode(&admin[..ADMIN_MSG_LEN - 1]),
        Err(DecodeError::TooShort { .. })
    ));
    assert!(matches!(Frame::decode(&admin[..4]), Err(DecodeError::TooShort { need: 5, got: 4 })));
}

#[test]
fn bad_magic_and_unknown_types_are_rejected() {
    let mut bytes = vector("text_wifi");
    bytes[0] = b'X';
    assert_eq!(Frame::decode(&bytes), Err(DecodeError::BadMagic));

    let mut bytes = vector("text_wifi");
    bytes[4] = 9;
    assert_eq!(Frame::decode(&bytes), Err(DecodeError::UnknownType(9)));
}

#[test]
fn oversized_text_length_is_rejected() {
    let mut bytes = vector("text_wifi");
    bytes[9..11].copy_from_slice(&201u16.to_le_bytes());
    assert_eq!(TextMsg::decode(&bytes), Err(DecodeError::TextTooLong(201)));

    let too_long = [b'x'; 201];
    assert_eq!(TextMsg::new(MsgType::Text, 0, &too_long), Err(DecodeError::TextTooLong(201)));
}

#[test]
fn captured_observation_payloads_parse_as_wardrive_lines() {
    // The round-trip test proves the frame layout survives; this proves the
    // payload format does. They fail independently: the firmware could change
    // its comma-separated line without touching the struct around it.
    use wartui_proto::air::{RecordKind, WardriveLine};

    let mut parsed = 0;
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')) {
        let name = line.split_whitespace().next().expect("name");
        let bytes = vector(name);
        let Ok(Frame::Text(msg)) = Frame::decode(&bytes) else { continue };
        // Heartbeats and pairing requests carry no payload.
        if msg.msg_type != MsgType::Text || msg.text.is_empty() {
            continue;
        }
        let record = WardriveLine::parse(msg.text)
            .unwrap_or_else(|e| panic!("{name}: {e} in {:?}", String::from_utf8_lossy(msg.text)));
        match record.kind {
            RecordKind::Ble => {
                assert_eq!(record.channel, 0, "{name}: BLE records carry channel 0");
                assert!(record.ssid.is_empty(), "{name}: BLE records carry no SSID");
            }
            RecordKind::Wifi => assert!(record.channel > 0, "{name}: Wi-Fi needs a real channel"),
        }
        assert!(record.rssi < 0, "{name}: RSSI should be negative dBm");
        parsed += 1;
    }
    assert!(parsed >= 3, "expected several observation payloads, parsed {parsed}");
}

#[test]
fn captured_payloads_re_encode_byte_for_byte() {
    // The node firmware writes these lines; the vendor's node wrote the ones in
    // this fixture. Reproducing them exactly — MAC case, empty fields, sign —
    // is what makes a wartui node's output indistinguishable downstream.
    use wartui_proto::air::{WARDRIVE_LINE_MAX, WardriveLine};

    let mut checked = 0;
    for line in GOLDEN.lines().filter(|l| !l.trim().is_empty() && !l.starts_with('#')) {
        let name = line.split_whitespace().next().expect("name");
        let bytes = vector(name);
        let Ok(Frame::Text(msg)) = Frame::decode(&bytes) else { continue };
        if msg.msg_type != MsgType::Text || msg.text.is_empty() {
            continue;
        }
        let record = WardriveLine::parse(msg.text).expect("a valid payload");
        let mut buf = [0u8; WARDRIVE_LINE_MAX];
        let len = record.write_into(&mut buf).expect("a captured line fits");
        assert_eq!(
            &buf[..len],
            msg.text,
            "{name}: re-encoded payload differs from what the node sent"
        );
        checked += 1;
    }
    assert!(checked >= 3, "expected several observation payloads, checked {checked}");
}
