name: Build & Test

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  wartui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --all-targets --all-features --locked --verbose

      - name: Clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings

      - name: Run tests
        run: cargo test --all-targets --all-features --locked --verbose

  firmware:
    strategy:
      matrix:
        target: [esp32c5, esp32c6]
        firmware_type: [bridge, node]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Lint
        run: |
          pushd firmware/${{matrix.firmware_type}}
          cargo fmt --all -- --check
          popd

      - name: Build
        run: |
          pushd firmware/${{matrix.firmware_type}}
          cargo build --release --features ${{matrix.target}} --locked --verbose
          popd

      - name: Clippy
        run: |
          pushd firmware/${{matrix.firmware_type}}
          cargo clippy --release --features ${{matrix.target}} --locked -- -D warnings
          popd

  firmware-s3-bridge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: esp-rs/xtensa-toolchain@v1.7
        with:
          buildtargets: esp32s3
          default: false
          override: false
          # `std` only; this firmware is `no_std`.
          ldproxy: false
          # Sets `xtensa-esp32s3-elf-gcc` on the PATH
          export: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Lint
        run: |
          pushd firmware/bridge
          cargo +esp fmt --all -- --check
          popd

      - name: Build
        run: |
          pushd firmware/bridge
          cargo +esp build --release --features esp32s3 --target xtensa-esp32s3-none-elf --locked --verbose
          popd

      - name: Clippy
        run: |
          pushd firmware/bridge
          cargo +esp clippy --release --features esp32s3 --target xtensa-esp32s3-none-elf --locked -- -D warnings
          popd
