name: Application

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  wartui:
    name: Wartui
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Lint
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --all-targets --all-features --locked --verbose

      - name: Clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings

      - name: Run tests
        run: cargo test --all-targets --all-features --locked --verbose
